### ISSUE TITLE
Nested objects cannot parse to string

### ISSUE THREAD

**Issue by WaveString** [catberry/catberry-uhr#12]
When I use contentType: 'application/x-www-form-urlencoded' and send POST params like this:
```
params = {
  okValue: 123,
  wrongValue: {
    one: 1,
    two: 2
  }
}
```
In browser: 
```
okValue: 123
wrongValue: [object Object]
```
It's not quite what I expected to see :)
It must be:
```
okValue: 123
wrongValue[one]:1
wrongValue[two]:2
```

**Comment by pragmadash** [comment]
What behaviour do you expect? How it should be represented in string?

**Comment by WaveString** [comment]
String represented like: 
```
okValue=1&wrongValue%5Bone%5D=1&wrongValue%5Btwo%5D=2
```

**Comment by pragmadash** [comment]
Could you find any usage of such approach in other platforms/frameworks? It would be nice to see details.

**Comment by WaveString** [comment]
Example usage with jquery. It's works with superagent also.
https://gist.github.com/WaveString/4baf140b92ce80c387bb

**Comment by chetverikov** [comment]
+1

**Comment by pragmadash** [comment]
Will be implemented here https://github.com/catberry/catberry-uri/issues/8
Closing.
