### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by wormen** [catberry/catberry-uhr#3]
Приветствую....
вопрос относится не совсем к этому модулю, но близко к теме .... 
и так ... вижу что текущий моль работает только с HTTP протоколом ... 
планируется ли разработка модуля для работы с socket.io, либо расширение текущего модуля, для работы с сокетами?

**Comment by pragmadash** [comment]
Этот модуль будет работать только с HTTP/HTTPS протоколом, разработка изоморфного модуля для работы с веб-сокетами пока не планируется.
