### ISSUE TITLE
Can i send files via UHR?

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry-uhr#5]

**Comment by pragmadash** [comment]
Unfortunately no, it's not implemented so far. I look forward to having `multipart/form-data` content type support in the future.

It's not that easy to implement. UHR is an isomorphic library and it should have the implementation for both the server and a browser. In a browser, we have the implementation of [FormData](https://developer.mozilla.org/en/docs/Web/API/FormData) that we can use. But on the server we have to implement [form data encoding](https://tools.ietf.org/html/rfc2183#section-3) or to use a 3rd-part library for that.

**Comment by slonofanya** [comment]
Maybe we can use functionality from https://github.com/mzabriskie/axios?

**Comment by pragmadash** [comment]
As I saw it can upload files only in a browser. Or maybe I missed something?

**Comment by slonofanya** [comment]
I didn't test in from node. 
But, i think in UHR it may be realised in browser, and then in node. What do you think?

**Comment by pragmadash** [comment]
That's not a problem to add file uploading for a browser in UHR. The hardest thing is to implement the same functionality on the server. We need to have the same API on both sides. 

I have a lack of time nowadays. So, I'll work on this maybe in a month.

Your help and PR is welcome.

**Comment by slonofanya** [comment]
Ok. If i will find the time - i will try to help with this.

**Comment by pragmadash** [comment]
Since [Catberry 8.0](https://github.com/catberry/catberry/releases/tag/8.0.0) release you can choose which library to use doing HTTP requests.

From my perspective, I would implement file uploading in an isomorphic way (on both the server and browser environments) but this task takes much time and has a very low priority now.

But as I said, PR is welcome!
